export default {
  'RU-AD': { titleEn: "Adygey", titleRu: 'Республика Адыгея' },
  'RU-ALT': { titleEn: "Altay", titleRu: 'Алтайский край' },
  'RU-AMU': { titleEn: "Amur", titleRu: 'Амурская область' },
  'RU-ARK': { titleEn: "Arkhangel'sk", titleRu: 'Архангельская область' },
  'RU-AST': { titleEn: "Astrakhan'", titleRu: 'Астраханская область' },
  'RU-BA': { titleEn: "Bashkortostan", titleRu: 'Республика Башкортостан' },
  'RU-BEL': { titleEn: "Belgorod", titleRu: 'Белгородская область' },
  'RU-BRY': { titleEn: "Bryansk", titleRu: 'Брянская область' },
  'RU-BU': { titleEn: "Buryat", titleRu: 'Республика Бурятия' },
  'RU-CE': { titleEn: "Chechnya", titleRu: 'Республика Чечня' },
  'RU-CHE': { titleEn: "Chelyabinsk", titleRu: 'Челябинская область' },
  'RU-CHU': { titleEn: "Chukot", titleRu: 'Чукотский автономный округ' },
  'RU-CU': { titleEn: "Chuvash", titleRu: 'Чувашская Республика' },
  'RU-DA': { titleEn: "Dagestan", titleRu: 'Республика Дагестан' },
  'RU-AL': { titleEn: "Gorno-Altay", titleRu: 'Республика Алтай' },
  'RU-IN': { titleEn: "Ingush", titleRu: 'Республика Ингушетия' },
  'RU-IRK': { titleEn: "Irkutsk", titleRu: 'Иркутская область' },
  'RU-IVA': { titleEn: "Ivanovo", titleRu: 'Ивановская область' },
  'RU-KB': { titleEn: "Kabardin-Balkar", titleRu: 'Кабардино-Балкария' },
  'RU-KC': { titleEn: "Karachay-Cherkess", titleRu: 'Карачаево-Черкесская Республика' },
  'RU-KDA': { titleEn: "Krasnodar", titleRu: 'Краснодарский край' },
  'RU-KEM': { titleEn: "Kemerovo", titleRu: 'Кемеровская область' },
  'RU-KLU': { titleEn: "Kaluga", titleRu: 'Калужская область' },
  'RU-KHA': { titleEn: "Khabarovsk", titleRu: 'Хабаровский край' },
  'RU-KR': { titleEn: "Karelia", titleRu: 'Республика Карелия' },
  'RU-KK': { titleEn: "Khakass", titleRu: 'Республика Хакасия' },
  'RU-KL': { titleEn: "Kalmyk", titleRu: 'Республика Калмыкия' },
  'RU-KHM': { titleEn: "Khanty-Mansiy", titleRu: 'Ханты-Мансийский автономный округ' },
  'RU-KGD': { titleEn: "Kaliningrad", titleRu: 'Калининградская область' },
  'RU-KO': { titleEn: "Komi", titleRu: 'Республика Коми' },
  'RU-KAM': { titleEn: "Kamchatka", titleRu: 'Камчатский край' },
  'RU-KRS': { titleEn: "Kursk", titleRu: 'Курская область' },
  'RU-KOS': { titleEn: "Kostroma", titleRu: 'Костромская область' },
  'RU-KGN': { titleEn: "Kurgan", titleRu: 'Курганская область' },
  'RU-KIR': { titleEn: "Kirov", titleRu: 'Кировская область' },
  'RU-KYA': { titleEn: "Krasnoyarsk", titleRu: 'Красноярский край' },
  'RU-LEN': { titleEn: "Leningrad", titleRu: 'Ленинградская область' },
  'RU-LIP': { titleEn: "Lipetsk", titleRu: 'Липецкая область' },
  'RU-MOW': { titleEn: "Moscow City", titleRu: 'Москва' },
  'RU-ME': { titleEn: "Mariy-El", titleRu: 'Марий Эл' },
  'RU-MAG': { titleEn: "Magadan", titleRu: 'Магаданская область' },
  'RU-MUR': { titleEn: "Murmansk", titleRu: 'Мурманская область' },
  'RU-MO': { titleEn: "Mordovia", titleRu: 'Мордовия' },
  'RU-MOS': { titleEn: "Moskva", titleRu: 'Московская область' },
  'RU-NGR': { titleEn: "Novgorod", titleRu: 'Новгородская область' },
  'RU-NEN': { titleEn: "Nenets", titleRu: 'Ненецкий автономный округ' },
  'RU-SE': { titleEn: "North Ossetia", titleRu: 'Республика Северная Осетия - Алания' },
  'RU-NVS': { titleEn: "Novosibirsk", titleRu: 'Новосибирская область' },
  'RU-NIZ': { titleEn: "Nizhegorod", titleRu: 'Нижегородская область' },
  'RU-ORE': { titleEn: "Orenburg", titleRu: 'Оренбургская область' },
  'RU-ORL': { titleEn: "Orel", titleRu: 'Орловская область' },
  'RU-OMS': { titleEn: "Omsk", titleRu: 'Омская область' },
  'RU-PER': { titleEn: "Perm'", titleRu: 'Пермский край' },
  'RU-PRI': { titleEn: "Primor'ye", titleRu: 'Приморский край' },
  'RU-PSK': { titleEn: "Pskov", titleRu: 'Псковская область' },
  'RU-PNZ': { titleEn: "Penza", titleRu: 'Пензенская область' },
  'RU-ROS': { titleEn: "Rostov", titleRu: 'Ростовская область' },
  'RU-RYA': { titleEn: "Ryazan'", titleRu: 'Рязанская область' },
  'RU-SAM': { titleEn: "Samara", titleRu: 'Самарская область' },
  'RU-SA': { titleEn: "Sakha", titleRu: 'Республика Саха (Якутия)' },
  'RU-SAK': { titleEn: "Sakhalin", titleRu: 'Сахалинская область' },
  'RU-SMO': { titleEn: "Smolensk", titleRu: 'Смоленская область' },
  'RU-SPE': { titleEn: "Saint Petersburg City", titleRu: 'Санкт-Петербург' },
  'RU-SAR': { titleEn: "Saratov", titleRu: 'Саратовская область' },
  'RU-STA': { titleEn: "Stavropol'", titleRu: 'Ставропольский край' },
  'RU-SVE': { titleEn: "Sverdlovsk", titleRu: 'Свердловская область' },
  'RU-TAM': { titleEn: "Tambov", titleRu: 'Тамбовская область' },
  'RU-TOM': { titleEn: "Tomsk", titleRu: 'Томская область' },
  'RU-TUL': { titleEn: "Tula", titleRu: 'Тульская область' },
  'RU-TA': { titleEn: "Tatarstan", titleRu: 'Республика Татарстан' },
  'RU-TY': { titleEn: "Tuva", titleRu: 'Республика Тыва' },
  'RU-TVE': { titleEn: "Tver'", titleRu: 'Тверская область' },
  'RU-TYU': { titleEn: "Tyumen'", titleRu: 'Тюменская область' },
  'RU-UD': { titleEn: "Udmurt", titleRu: 'Республика Удмуртия' },
  'RU-ULY': { titleEn: "Ul'yanovsk", titleRu: 'Ульяновская область' },
  'RU-VGG': { titleEn: "Volgograd", titleRu: 'Волгоградская область' },
  'RU-VLA': { titleEn: "Vladimir", titleRu: 'Владимирская область' },
  'RU-YAN': { titleEn: "Yamal-Nenets", titleRu: 'Ямало-Ненецкий автономный округ' },
  'RU-VLG': { titleEn: "Vologda", titleRu: 'Вологодская область' },
  'RU-VOR': { titleEn: "Voronezh", titleRu: 'Воронежская область' },
  'RU-YAR': { titleEn: "Yaroslavl'", titleRu: 'Ярославская область' },
  'RU-YEV': { titleEn: "Yevrey", titleRu: 'Еврейский автономный округ' },
  'RU-ZAB': { titleEn: "Zabaykal'ye", titleRu: 'Забайкальский край' },
}
